server:
  port: 9070

app:
  couchbase:
    connection-string: couchbase://localhost
    user-name: Administrator
    password: password
    bucketName: trade-service
    scopeName: dev

spring:
  application:
    name: cedar-agent
  graphql:
    graphiql:
      enabled: true
  main:
    web-application-type: reactive
  webflux:
    base-path: /api/trade-service

logging:
  level:
    org.springframework.data.couchbase.core: TRACE